### PR TITLE
clarifying spec fixes for queries

### PR DESCRIPTION
**Pull request by mbj4668**
## Proposed Changes

More spec fixes.  Previoulsy, most of the query functions were speced like:

                ra_server_proc:ra_leader_call_ret(term()) |
                {ok, {ra_idxterm(), term()}, not_known}

This is type-correct, but a bit confusing.  The term() in the first row is really {ra_idxterm(), Reply}.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x ] I have read the `CONTRIBUTING.md` document
- [x ] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by mbj4668** [comment]
I'm sorry, I ran the wrong dialyzer tests...  I will fix this.

**Comment by mbj4668** [comment]
Perhaps the documentation for local_query() and leader_query() can explain what the ra_idxterm() is and how it is useful.  Why isn't it returned from consistent_query()?

**Comment by michaelklishin** [comment]
Reference docs generally should not explain concepts, in particular if it's of little use most of the time.

**Comment by michaelklishin** [comment]
While I don't know if there is a specific reason, `consistent_query/{2,3}` is a version of `leader_query/{2,3}` in that it checks that the current leader still, in fact, is the leader. If that's the case you probably don't need the term information.

With a query type that can return stale data such as `local_query/2` you potentially need it to be able to determine if the data is stale. Since you are explicitly telling Ra to not go through the leader with extra consensus checks, it's up to your application to do that.

**Comment by michaelklishin** [comment]
Ra needs a set of guides which I hope to be able to contribute to. 
Thank you!

**Pull request merged**
