### PR TITLE
Metrics tweaks and meta data optimisations

### PR DESCRIPTION
**Pull request by kjnilsson**
Allow the metrics key to be specified through config.

Also a commit to reduce cpu use of the meta data store in low/medium throughput scenarios.

### CODE REVIEW

**Comment by gerhard** [comment]
When put together, this is the current state of this:

image

**Comment by michaelklishin** [comment]
Should this be merged then? ;)

**Comment by michaelklishin** [comment]
:shipit:

**Comment by gerhard** [comment]
That's the first thing that we intend to do today, with a fresh pair of eyes. 👍 👀

**Pull request merged**
